## ----------------------------------
## ..:: App2 app in Arcadia UNIT ::..
## ----------------------------------
apiVersion: v1
kind: Service
metadata:
  name: arcadia-unit-app2
  namespace: arcadia-unit
  labels:
    app: arcadia-unit-app2
spec:
  type: ClusterIP
  ports:
  - name: arcadia-app2-unit-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
      app: arcadia-unit-app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-unit-app2
  namespace: arcadia-unit
  labels:
    app: arcadia-unit-app2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-unit-app2
      version: v1
  template:
    metadata:
      labels:
        app: arcadia-unit-app2
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: arcadia-unit-app2
        image: docker.io/madhukar32/arcadia-app2:unit
        imagePullPolicy: Always
        name: arcadia-unit-app2
        ports:
        - containerPort: 8080
          protocol: TCP