apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: arcadia-unit-vs
  namespace: arcadia
spec:
  host: www.arcadia-finance.io
  upstreams:
  - name: arcadia-main
    service: arcadia-unit-main
    port: 80
  - name: arcadia-app2
    service: arcadia-unit-app2
    port: 80
  - name: arcadia-app3
    service: arcadia-app3
    port: 80
  routes:
  - path: /
    action:
      pass: arcadia-main
  - path: /api
    action:
      pass: arcadia-app2
  - path: /app3
    action:
      pass: arcadia-app3
